# Generated by Django 3.1.7 on 2021-04-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clutch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintings',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
